using System;

namespace Cosmonaut.Attributes
{
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
    public class CosmosIdAttribute : Attribute
    {
        public bool AutoGenerated { get; set; }

        public CosmosIdAttribute() : this (true)
        {
            
        }

        public CosmosIdAttribute(bool autoGenerated)
        {
            AutoGenerated = autoGenerated;
        }
    }
}