using System;
using Newtonsoft.Json;

namespace Cosmonaut
{
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
    public class CosmosIdAttribute : Attribute
    {
        public bool AutoGenerated { get; set; }

        public CosmosIdAttribute() : this (true)
        {
            
        }

        public CosmosIdAttribute(bool autoGenerated)
        {
            AutoGenerated = autoGenerated;
        }
    }
}